#**K-Nearest Neighbour**

In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [20]:
solar_dataset = pd.read_excel('Dataset_set_for_classification.xlsx')

In [21]:
solar_dataset

1      2     3           4            5             6   \
0     YEAR  MONTH  DATE  RADIO FLUX  SUN SPOT NO  SUNSPOT AREA   
1     1997      6     2          77           35           120   
2     1997      6     3          75           20           150   
3     1997      6     4          74           16           110   
4     1997      6     5          74           15           120   
...    ...    ...   ...         ...          ...           ...   
8375  2020      5     6          70            0             0   
8376  2020      5     7          69            0             0   
8377  2020      5     8          68            0             0   
8378  2020      5     9          71            0             0   
8379  2020      5    10          68            0             0   

                         7                8                9   \
0     X-RAY BACKGROUND FLUX  PROTON FLUENCES  PROTON FLUENCES   
1                       4.5           340000            18000   
2                       4.2           330000            18000   
3                       3.6           350000            18000   
4                       2.2           350000            19000   
...                     ...              ...              ...   
8375                      0            54000            46000   
8376                      0            66000            46000   
8377                      0            81000            46000   
8378                      0            76000            46000   
8379                      0           260000            46000   

                   10  ... 47 48 49 50 51 52 53 54           55             56  
0     PROTON FLUENCES  ...  c  m  x  s  1  2  3  4  x-ray class  optical class  
1                4600  ...  0  0  0  0  0  0  0  0            0              0  
2                4400  ...  0  0  0  0  0  0  0  0            0              0  
3                4500  ...  0  0  0  0  0  0  0  0            0              0  
4                4600  ...  0  0  0  0  0  0  0  0            0              0  
...               ...  ... .. .. .. .. .. .. .. ..          ...            ...  
8375             3200  ...  0  0  0  0  0  0  0  0            0              0  
8376             3200  ...  0  0  0  0  0  0  0  0            0              0  
8377             3200  ...  0  0  0  0  0  0  0  0            0              0  
8378             3200  ...  0  0  0  0  0  0  0  0            0              0  
8379             3200  ...  0  0  0  0  0  0  0  0            0              0  

[8380 rows x 56 columns]

# For c-class solar flares

In [22]:
X = solar_dataset.iloc[1:, 0:38].values
y = solar_dataset.iloc[1:, 46].values

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [24]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [25]:
y_train=np.asarray(y_train,dtype=float)

In [26]:
# Fitting K-NN to the Training setD
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [27]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [28]:
y_test=np.asarray(y_test,dtype=int)

In [29]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1426,  224],
       [ 373, 1329]], dtype=int64)

In [30]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.86      0.83      1650
           1       0.86      0.78      0.82      1702

    accuracy                           0.82      3352
   macro avg       0.82      0.82      0.82      3352
weighted avg       0.82      0.82      0.82      3352



#For m-class solar flares

Not using c-class flare data

In [31]:
X = solar_dataset.iloc[1:, 0:38].values
y = solar_dataset.iloc[1:, 47].values

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [33]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [34]:
y_train=np.asarray(y_train,dtype=float)

In [35]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [36]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [37]:
y_test=np.asarray(y_test,dtype=int)

In [38]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1378,   46],
       [ 199,   53]], dtype=int64)

In [39]:
#for n=3  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1424
           1       0.54      0.21      0.30       252

    accuracy                           0.85      1676
   macro avg       0.70      0.59      0.61      1676
weighted avg       0.82      0.85      0.83      1676



In [40]:
#for n=5  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1424
           1       0.54      0.21      0.30       252

    accuracy                           0.85      1676
   macro avg       0.70      0.59      0.61      1676
weighted avg       0.82      0.85      0.83      1676



In [41]:
#for n=10  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1424
           1       0.54      0.21      0.30       252

    accuracy                           0.85      1676
   macro avg       0.70      0.59      0.61      1676
weighted avg       0.82      0.85      0.83      1676



In [42]:
# For n=5 and train:test = 8:2
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1424
           1       0.54      0.21      0.30       252

    accuracy                           0.85      1676
   macro avg       0.70      0.59      0.61      1676
weighted avg       0.82      0.85      0.83      1676



**Using c-class Solar flare data**

In [43]:
X = solar_dataset.iloc[1:, 0:39].values
y = solar_dataset.iloc[1:, 47].values

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [45]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [46]:
y_train=np.asarray(y_train,dtype=float)

In [47]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [48]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [49]:
y_test=np.asarray(y_test,dtype=int)

In [50]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[2754,  104],
       [ 375,  119]], dtype=int64)

In [51]:
#for n=5  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      2858
           1       0.53      0.24      0.33       494

    accuracy                           0.86      3352
   macro avg       0.71      0.60      0.63      3352
weighted avg       0.83      0.86      0.83      3352



In [52]:
#for n=5  train:test = 8:2
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      2858
           1       0.53      0.24      0.33       494

    accuracy                           0.86      3352
   macro avg       0.71      0.60      0.63      3352
weighted avg       0.83      0.86      0.83      3352



#**For x-class solar flares**

**Not using c-class & m-class Solar flares data**

In [53]:
X = solar_dataset.iloc[1:, 0:38].values
y = solar_dataset.iloc[1:, 48].values

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [55]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [56]:
y_train=np.asarray(y_train,dtype=float)

In [57]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [58]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [59]:
y_test=np.asarray(y_test,dtype=int)

In [60]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1648,    0],
       [  27,    1]], dtype=int64)

In [61]:
#for n=5  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1648
           1       1.00      0.04      0.07        28

    accuracy                           0.98      1676
   macro avg       0.99      0.52      0.53      1676
weighted avg       0.98      0.98      0.98      1676



In [62]:
#for n=5  train:test = 8:2
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1648
           1       1.00      0.04      0.07        28

    accuracy                           0.98      1676
   macro avg       0.99      0.52      0.53      1676
weighted avg       0.98      0.98      0.98      1676



**Using c-class Solar flares data**

In [63]:
X = dataset.iloc[1:, 0:39].values
y = dataset.iloc[1:, 48].values

NameError: name 'dataset' is not defined

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [ ]:
y_train=np.asarray(y_train,dtype=float)

In [ ]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [ ]:
y_test=np.asarray(y_test,dtype=int)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1648,    0],
       [  27,    1]])

In [ ]:
#for n=5  train:test = 5:5
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      4115
           1       0.67      0.03      0.05        75

    accuracy                           0.98      4190
   macro avg       0.82      0.51      0.52      4190
weighted avg       0.98      0.98      0.97      4190



In [ ]:
#for n=5  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      3292
           1       0.67      0.03      0.06        60

    accuracy                           0.98      3352
   macro avg       0.82      0.52      0.53      3352
weighted avg       0.98      0.98      0.97      3352



In [ ]:
#for n=5  train:test = 8:2
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1648
           1       1.00      0.04      0.07        28

    accuracy                           0.98      1676
   macro avg       0.99      0.52      0.53      1676
weighted avg       0.98      0.98      0.98      1676



**Using c-class & m-class Solar flares data**

In [ ]:
X = solar_dataset.iloc[1:, 0:40].values
y = solar_dataset.iloc[1:, 48].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [ ]:
y_train=np.asarray(y_train,dtype=float)

In [ ]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [ ]:
y_test=np.asarray(y_test,dtype=int)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

In [ ]:
#for n=5  train:test = 5:5
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      4115
           1       0.75      0.04      0.08        75

    accuracy                           0.98      4190
   macro avg       0.87      0.52      0.53      4190
weighted avg       0.98      0.98      0.97      4190



In [ ]:
#for n=5  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      3292
           1       0.75      0.05      0.09        60

    accuracy                           0.98      3352
   macro avg       0.87      0.52      0.54      3352
weighted avg       0.98      0.98      0.98      3352

